# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file.

## Objectives
You will be able to:

- Use pandas to import data from a CSV and and an Excel spreadsheet  

##  Loading Files with Summary or Meta Data

Load either of the files `'Zipcode_Demos.csv'` or `'Zipcode_Demos.xlsx'`. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled `'Data'`.

In [2]:
!git clone https://github.com/dbvimpec/dsc-importing-data-using-pandas-lab

Cloning into 'dsc-importing-data-using-pandas-lab'...
remote: Enumerating objects: 248, done.
remote: Counting objects: 100% (248/248), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 248 (delta 154), reused 243 (delta 153), pack-reused 0 (from 0)
Receiving objects: 100% (248/248), 1.83 MiB | 8.28 MiB/s, done.
Resolving deltas: 100% (154/154), done.

In [3]:
# Import pandas using the standard alias
import pandas as pd

In [11]:
# Import the file and print the first 5 rows
df = pd.read_csv('/content/dsc-importing-data-using-pandas-lab/Data/Zipcode_Demos.csv')
df.head()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Print the last 5 rows of df
df.tail()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [17]:
# What is going on with this data set? Anything unusual?
df.info()

# Comment: Dataframe is really two table views, one on top of the other.
# The first is a summary view of the raw data below.
# There is also a blank row at row 1 in the file.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 47 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   0                   57 non-null     int64
 1   Average Statistics  56 non-null     object
 2   Unnamed: 2          57 non-null     object
 3   Unnamed: 3          11 non-null     object
 4   Unnamed: 4          11 non-null     object
 5   Unnamed: 5          11 non-null     object
 6   Unnamed: 6          11 non-null     object
 7   Unnamed: 7          11 non-null     object
 8   Unnamed: 8          11 non-null     object
 9   Unnamed: 9          11 non-null     object
 10  Unnamed: 10         11 non-null     object
 11  Unnamed: 11         11 non-null     object
 12  Unnamed: 12         11 non-null     object
 13  Unnamed: 13         11 non-null     object
 14  Unnamed: 14         11 non-null     object
 15  Unnamed: 15         11 non-null     object
 16  Unnamed: 16         11 non-null     object
 17  Unnamed: 17         11 non-null     object
 18  Unnamed: 18         11 non-null     object
 19  Unnamed: 19         11 non-null     object
 20  Unnamed: 20         11 non-null     object
 21  Unnamed: 21         11 non-null     object
 22  Unnamed: 22         11 non-null     object
 23  Unnamed: 23         11 non-null     object
 24  Unnamed: 24         11 non-null     object
 25  Unnamed: 25         11 non-null     object
 26  Unnamed: 26         11 non-null     object
 27  Unnamed: 27         11 non-null     object
 28  Unnamed: 28         11 non-null     object
 29  Unnamed: 29         11 non-null     object
 30  Unnamed: 30         11 non-null     object
 31  Unnamed: 31         11 non-null     object
 32  Unnamed: 32         11 non-null     object
 33  Unnamed: 33         11 non-null     object
 34  Unnamed: 34         11 non-null     object
 35  Unnamed: 35         11 non-null     object
 36  Unnamed: 36         11 non-null     object
 37  Unnamed: 37         11 non-null     object
 38  Unnamed: 38         11 non-null     object
 39  Unnamed: 39         11 non-null     object
 40  Unnamed: 40         11 non-null     object
 41  Unnamed: 41         11 non-null     object
 42  Unnamed: 42         11 non-null     object
 43  Unnamed: 43         11 non-null     object
 44  Unnamed: 44         11 non-null     object
 45  Unnamed: 45         11 non-null     object
 46  Unnamed: 46         11 non-null     object
dtypes: int64(1), object(46)
memory usage: 21.1+ KB

In [20]:
# Clean up the dataset

prev_count = 10**3
for row in df.index:
    count = 0
    for entry in df.iloc[row].isnull():
        if entry:
            count += 1
    if count != prev_count and row!=0:
        print(f'On row {row} there are {count} null values. The previous row had {prev_count} null values.')
    prev_count = count

On row 1 there are 44 null values. The previous row had 45 null values.
On row 46 there are 0 null values. The previous row had 44 null values.

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encounter some really ill-formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and the commas within those fields themselves. For example, we could have a table like this:  

`ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765`

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
`"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"`

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled `'Yelp_Reviews_Corrupt.csv'`. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [24]:
# Hint: Here's a useful programming pattern to use
# Your code here
try:
    df = pd.read_csv('/content/dsc-importing-data-using-pandas-lab/Data/Yelp_Reviews_Corrupt.csv')
except Exception as e:
    print(e)

Error tokenizing data. C error: Expected 10 fields in line 2331, saw 11

In [25]:
# # Iteration 1
for i in range(1500,2000):
    try:
        df = pd.read_csv('/content/dsc-importing-data-using-pandas-lab/Data/Yelp_Reviews_Corrupt.csv', nrows=i)
    except:
        print(f'First failure at: {i}')
        break
df1 = pd.read_csv('/content/dsc-importing-data-using-pandas-lab/Data/Yelp_Reviews_Corrupt.csv', nrows=i-1)
print(len(df))
df1.head()

First failure at: 1962
1961

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0.0,dDl8zu1vWPdKGihJrwQbpw,5.0,I love this place! My fiance And I go here atl...,0.0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1.0,LZp4UX5zK3e-c5ZGSeo3kA,1.0,Terrible. Dry corn bread. Rib tips were all fa...,3.0,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0.0,jsDu6QEJHbwP2Blom1PLCA,5.0,Delicious healthy food. The steak is amazing. ...,0.0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0.0,pfavA0hr3nyqO61oupj-lA,1.0,This place sucks. The customer service is horr...,2.0,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0.0,STiFMww2z31siPY7BWNC2g,5.0,I have been an Emerald Club member for a numbe...,0.0,TlvV-xJhmh7LCwJYXkV-cg

In [26]:
df.tail()

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1956,4993,u8C8pRvaHXg3PgDrsUHJHQ,0,2016-08-08,0.0,gXmHGBSBBz2-uHdvGf4lZQ,2.0,just went to a retirement party upstairs and t...,1.0,tFa-r1pxZh04FjxNSEQgcQ
1957,4998,-9nai28tnoylwViuJVrYEQ,0,2015-03-22,0.0,u-zqCN_IXfypJIUzIVUuzw,5.0,Great restaurant and great atmosphere.,NaN,NaN
1958,I had an awesome great time with friends.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1959,I loved the tapas and the excellent paella.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1960,I can't wait to come back soon.,0,otDVyX37h61WEbqPLEjCmQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# # Iteration 2
for i in range(0,500):
    try:
        temp = pd.read_csv('/content/dsc-importing-data-using-pandas-lab/Data/Yelp_Reviews_Corrupt.csv', skiprows=1962, nrows=i, names=df1.columns)
    except:
        print(f'First failure at: {i}')
        break
df2 = pd.read_csv('/content/dsc-importing-data-using-pandas-lab/Data/Yelp_Reviews_Corrupt.csv', skiprows=1962, nrows=i-1, names=df1.columns)
print(len(df2))
df2.head()

First failure at: 341
340

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,STAY AWAY FROM THIS PLACE!!!!!!,5,sDofYImMQQmu4Le5G9zmpQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3948,GAKFx4jFUtTOTpp_jDJnuA,0,2017-09-01,0.0,OUZWMw7EgO7D596pUelSlA,5.0,Nice relaxing atmosphere. Friendly service and...,1.0,6vJY67yve43Ijvn8RKVUow
2,3949,0QzCeORfF8EY34UODWRV9A,0,2017-09-03,0.0,7lbykaWFD8YBwT0mU1Rexw,4.0,Very pleased with our experience. Great off th...,0.0,6vJY67yve43Ijvn8RKVUow
3,3950,tlt8zNrZ6_A3DmXiM-cnBA,0,2016-06-12,0.0,Nd_soHwCYi8adcNIT2w9LQ,1.0,Wife went to this location and was horrible. N...,0.0,S0dnPb1OzaqdBSOxyLr7BQ
4,3952,XD0LjNuPPwJPsTAHecUh7A,0,2015-08-23,0.0,FUUTAr5CECrkfRa9Y2-MSg,1.0,Not baby friendly anymore.,NaN,NaN

In [30]:
temp = pd.read_csv('dsc-importing-data-using-pandas-lab/Data/Yelp_Reviews_Corrupt.csv', names=df1.columns, skiprows=1)
print(len(temp))
temp.head()

ParserError: Error tokenizing data. C error: Expected 10 fields in line 2331, saw 11

In [32]:
pd.read_csv('/content/dsc-importing-data-using-pandas-lab/Data/Yelp_Reviews_Corrupt.csv', skiprows=len(df1)+len(df2), names=df1.columns)

ParserError: Error tokenizing data. C error: Expected 10 fields in line 2331, saw 11

## Summary

Congratulations, you now practiced your Pandas-importing skills.